[
  {
    key: "cita",
    label: "Citas",
    isTitle: true,
  },
  {
    key: "crear-cita-nut",
    label: "Citas nutricionista",
    isTitle: false,
    icon: "uil-calender",
    url: "/crear-citas-nutricion",
  },
  {
    key: "hist-citas-NUT",
    label: "Historial de citas nutricionista",
    isTitle: false,
    icon: "uil-calender",
    url: "/history-citas-nutricion",
  },
  {
    key: "ventas",
    label: "Ventas",
    isTitle: true,
  },
  {
    key: "ventas-nuevaVenta",
    label: "Nueva venta",
    isTitle: false,
    icon: "uil-calender",
    url: "/nueva-venta",
  },
  {
    key: "ventas-seguimiento",
    label: "Seguimiento",
    isTitle: false,
    icon: "uil-calender",
    url: "/seguimiento",
  },
  {
    key: "cliente",
    label: "SOCIO",
    isTitle: true,
  },
  {
    key: "cliente-contratos",
    label: "Contratos de socios",
    isTitle: false,
    icon: "uil-calender",
    url: "/contrato-clientes",
  },
  {
    key: "cliente-admClientes",
    label: "Gestion de socios",
    isTitle: false,
    icon: "uil-calender",
    url: "/gestion-clientes",
  },
  {
    key: "cliente-prospecto",
    label: "Prospectos",
    isTitle: false,
    icon: "uil-calender",
    url: "/gestion-prospecto",
  },

  {
    key: "cong-reg",
    label: "Congelamiento y Regalo",
    isTitle: true,
  },
  {
    key: "congreg",
    label: "Congelamiento y regalos",
    isTitle: false,
    icon: "uil-calender",
    url: "/extension-membresia",
  },
  //ADMIN
  {
    key: "reporte-admin",
    label: "Reporte de Utilidad",
    isTitle: true,
  },
  {
    key: "reporte-utilidad-pgm",
    label: "Por programas",
    isTitle: false,
    icon: "uil-calender",
    url: "/reporte-admin/reporte-utilidad-programa",
  },
  {
    key: "reporte-utilidad-sup",
    label: "Por suplementos",
    isTitle: false,
    icon: "uil-calender",
    url: "/reporte-admin/reporte-utilidad-supl",
  },
  {
    key: "reporte-utilidad-acc",
    label: "Por accesorios",
    isTitle: false,
    icon: "uil-calender",
    url: "/reporte-admin/reporte-utilidad-acc",
  },
  {
    key: "reporte-utilidad-trat-estetico",
    label: "Por tratamientos esteticos",
    isTitle: false,
    icon: "uil-calender",
    url: "/reporte-admin/reporte-utilidad-trat-estetico",
  },
  {
    key: "reporte-utilidad-nutricion",
    label: "Por nutricionista",
    isTitle: false,
    icon: "uil-calender",
    url: "/reporte-admin/reporte-utilidad-nutricionista",
  },
  {
    key: "config",
    label: "Recursos Humanos",
    isTitle: true,
  },
  {
    label: "Reportes Por Planilla",
    isTitle: false,
    icon: "uil-calender",
    url: "/reporte-admin/RecursosHumanoReportes",
  },
  {
    key: "reporte-utilidad-pgm",
    label: "Reporte de asistencias",
    isTitle: false,
    icon: "uil-calender",
    url: "/reporte-admin/asistenciaReporte",
  },
  {
    key: "config",
    label: "INVENTARIO",
    isTitle: true,
  },
  {
    //key: "reporte-utilidad-pgm",
    label: "GESTION DE INVENTARIO",
    isTitle: false,
    icon: "uil-calender",
    url: "/gest-inventario",
  },
  {
    //key: "reporte-utilidad-pgm",
    label: "ENTRADA DE ITEMS",
    isTitle: false,
    icon: "uil-calender",
    url: "/entrada-inventario",
  },
  {
    //key: "reporte-utilidad-pgm",
    label: "SALIDA DE ITEMS",
    isTitle: false,
    icon: "uil-calender",
    url: "/salida-inventario",
  },
  {
    //key: "reporte-utilidad-pgm",
    label: "TRANSFERENCIA DE ITEMS",
    isTitle: false,
    icon: "uil-calender",
    url: "/transferencia-inventario",
  },
  {
    //key: "reporte-utilidad-pgm",
    label: "INVENTARIO TOTALIZADO",
    isTitle: false,
    icon: "uil-calender",
    url: "/totalizado-inventario",
  },
  {
    //key: "reporte-utilidad-pgm",
    label: "GENERADOR DE FECHAS INVENTARIO",
    isTitle: false,
    icon: "uil-calender",
    url: "/generador-fechas-inventario",
  },
  {
    key: "reporte-admin",
    label: "Reportes",
    isTitle: true,
  },
  {
    key: "reporte-utilidad-pgm",
    label: "Planilla",
    isTitle: false,
    icon: "uil-calender",
    url: "/reporte-admin/RecursosHumanoReportes",
  },
  {
    key: "reporte-flujo-caja",
    label: "FLUJO DE CAJA",
    isTitle: false,
    icon: "uil-calender",
    url: "/reporte-admin/flujo-caja",
  },
  {
    key: "reporte-comparativa-dia",
    label: "Comparativo por dia",
    isTitle: false,
    icon: "uil-calender",
    url: "/reporte-admin/comparativa-dia",
  },
  {
    key: "reporte-egresos",
    label: "Egresos",
    isTitle: false,
    icon: "uil-calender",
    url: "/reporte-admin/reporte-egresos",
  },
  {
    key: "reporte-gerencial",
    label: "Gerencial",
    isTitle: false,
    icon: "uil-calender",
    url: "/reporte-admin/reporte-gerencial",
  },
  {
    key: "reporte-gerencial",
    label: "Reporte de Clientes",
    isTitle: false,
    icon: "uil-calender",
    url: "/reporte-admin/ReportePorMarcacion",
  },
  {
    key: "gf-gv",
    label: "Egresos y Aportes",
    isTitle: true,
  },
  {
    key: "gestion-gfgv",
    label: "Registro de compra",
    isTitle: false,
    icon: "uil-calender",
    url: "/orden-compra",
  },
  {
    key: "gestion-gfgv",
    label: "Egresos",
    isTitle: false,
    icon: "uil-calender",
    url: "/gestion-gastosF-gastosV",
  },
  {
    key: "gestion-gfgv",
    label: "Aportes",
    isTitle: false,
    icon: "uil-calender",
    url: "/aporte-ingresos",
  },
  {
    key: "prov",
    label: "Proveedores",
    isTitle: true,
  },
  {
    key: "gest-prov",
    label: "Gestion de proveedores",
    isTitle: false,
    icon: "uil-calender",
    url: "/gestion-proveedores",
  },
  {
    key: "trab-prov",
    label: "gastos ",
    isTitle: false,
    icon: "uil-calender",
    url: "/proveedores/prov-agentes",
  },
  {
    key: "planilla",
    label: "RECURSOS HUMANOS",
    isTitle: true,
  },
  {
    key: "colaboradores-admColaboradores",
    label: "Colaboradores",
    isTitle: false,
    icon: "uil-calender",
    url: "/gestion-empleados",
  },
  {
    key: "gest-serv",
    label: "Gestion de servicios",
    isTitle: true,
  },
  {
    key: "gestion-pgms",
    label: "Gestion de programas",
    isTitle: false,
    icon: "uil-calender",
    url: "/gestion-programas",
  },
  {
    key: "gestion-prds",
    label: "Productos",
    isTitle: false,
    icon: "uil-calender",
    url: "/gestion-productos",
  },
  {
    key: "serv-fito",
    label: "Fitology",
    isTitle: false,
    icon: "uil-calender",
    url: "/serv-fitology",
  },
  {
    key: "serv-nutri",
    label: "Nutricion",
    isTitle: false,
    icon: "uil-calender",
    url: "/serv-nutricion",
  },
  {
    key: "planilla",
    label: "Otros",
    isTitle: true,
  },
  {
    key: "adm-gestionDct",
    label: "Impuestos",
    isTitle: false,
    icon: "uil-calender",
    url: "/gestion-descuentos",
  },
  {
    key: "adm-gestionComisional",
    label: "Comisiones",
    isTitle: false,
    icon: "uil-calender",
    url: "/gestion-comisional",
  },
  {
    key: "config",
    label: "Configuracion",
    isTitle: true,
  },
  {
    key: "adm-usuario",
    label: "Administrar usuarios",
    isTitle: false,
    icon: "uil-calender",
    url: "/gestion-auth-usuario",
  },
  {
    key: "gest-jornada",
    label: "Gestion de jornadas",
    isTitle: false,
    icon: "uil-calender",
    url: "/gest-jornada",
  },
  {
    key: "adm-audit",
    label: "Auditoria",
    isTitle: false,
    icon: "uil-calender",
    url: "/auditoria",
  },
  {
    key: "conf-term",
    label: "Terminologias",
    isTitle: false,
    icon: "uil-calender",
    url: "/configuracion-terminos",
  },
  {
    key: "conf-tip-cambio",
    label: "Tipo de cambio",
    isTitle: false,
    icon: "uil-calender",
    url: "/tipo-cambio",
  },
];
